name: derivative-tinygp
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - matplotlib-inline=0.1.7
  - pip=24.0
  - python=3.11.4
  - pip:
    - -r requirements.txt
